using System.Windows;

namespace Oi.Forms
{
    /// <summary>
    /// Provides a dialog for generating bypass codes
    /// from request codes.
    /// </summary>
    public partial class BypassCodeGenerator : Window
    {
        /// <summary>
        /// The message displayed to the user explaining the request.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="BypassCodeGenerator"/> class.
        /// </summary>
        public BypassCodeGenerator()
        {
            InitializeComponent();
            this.Topmost = true;
            this.ShowInTaskbar = true;

            this.Message = "Enter a bypass request code provided to you by a user. " +
                "You will get a generated bypass code that the user can then " +
                "use to bypass a specified set of Elements of their protection.";

            DataContext = this;
        }


        /// <summary>
        /// Generates an authorization code for the supplied user name.
        /// </summary>
        /// <param name="sender">The button click sender.</param>
        /// <param name="e">The routed event arguments.</param>
        private void GenerateButton_Click(object sender, RoutedEventArgs e)
        {
            string requestCode = BypassRequestTextBox.Text.Trim();

            if (requestCode.Ext_HasNoChars())
            {
                BypassRequestTextBox.Text = "Enter a request code.";
                return;
            }

            BypassTextBox.Text = Authorization.BuildActualBypassCode(requestCode);
        }


        /// <summary>
        /// Copies the generated bypass code to the clipboard.
        /// </summary>
        /// <param name="sender">The button click sender.</param>
        /// <param name="e">The routed event arguments.</param>
        private void CopyButton_Click(object sender, RoutedEventArgs e)
        {
            if (BypassTextBox.Text.Ext_HasNoChars())
            {
                return;
            }

            BypassTextBox.Text.Ext_SendToClipboard();
        }
    }
}