//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oi.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oi.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools related to administrating access to Oi&apos;s Tab, and permitting user&apos;s to bypass protection when required..
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays basic information about the AddIn, and provides a means to directly access the related project GitHub..
        /// </summary>
        internal static string Admin_About {
            get {
                return ResourceManager.GetString("Admin_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a form to enter a user&apos;s name and get the corresponding request response code that Oi will look for in that user&apos;s Local AppData folder when Revit launches..
        /// </summary>
        internal static string Admin_GetAdminCode {
            get {
                return ResourceManager.GetString("Admin_GetAdminCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a form to enter a bypass request code, which will generate a response code that can be used to enable the protection bypass.
        ///
        ///Note that this code will be unique to the Elements involved in the request, so will only work for the specific bypass being attempted..
        /// </summary>
        internal static string Admin_GetBypassCode {
            get {
                return ResourceManager.GetString("Admin_GetBypassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers you as an Administrator, which will write a request response code to your Local AppData folder. When Revit boots up, Oi will look at this folder to determine if a user is an Administrator.
        ///
        ///If this file is not found with a valid code, Oi will load in low trust mode without access to its Tools ribbon..
        /// </summary>
        internal static string Admin_SelfAppointAsAdmin {
            get {
                return ResourceManager.GetString("Admin_SelfAppointAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools related to protecting Elements from deletion..
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a form that provides information about protected Elements in the current Document, including when, who and why the Elements were protected.
        ///
        ///This form will be presented to users if they attempt to delete protected Elements as well..
        /// </summary>
        internal static string Delete_ProtectionReview {
            get {
                return ResourceManager.GetString("Delete_ProtectionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies protection to any selected Element(s) without it currently of this type. You will be prompted to also provide a basic summary of the purpose of protection, so that end users have a better understanding of why they may encounter prevention mechanisms in future..
        /// </summary>
        internal static string Delete_ProtectSelectedElements {
            get {
                return ResourceManager.GetString("Delete_ProtectSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects all Elements in the current Document that currently have protection applied from being deleted..
        /// </summary>
        internal static string Delete_SelectProtectedElements {
            get {
                return ResourceManager.GetString("Delete_SelectProtectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes protection from any selected Element(s) with it currently of this type. This tool can only be ran by administrators as it does not trigger a bypass code to be validated unlike if an end user tries to bypass protection when offered..
        /// </summary>
        internal static string Delete_UnprotectSelectedElements {
            get {
                return ResourceManager.GetString("Delete_UnprotectSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools related to protecting Elements from modification. Note that Elements protected in this way can still be deleted unless they also have Delete protection applied..
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a form that provides information about protected Elements in the current Document, including when, who and why the Elements were protected.
        ///
        ///This form will be presented to users if they attempt to modify protected Elements as well..
        /// </summary>
        internal static string Modify_ProtectionReview {
            get {
                return ResourceManager.GetString("Modify_ProtectionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies protection to any selected Element(s) without it currently of this type. You will be prompted to also provide a basic summary of the purpose of protection, so that end users have a better understanding of why they may encounter prevention mechanisms in future..
        /// </summary>
        internal static string Modify_ProtectSelectedElements {
            get {
                return ResourceManager.GetString("Modify_ProtectSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects all Elements in the current Document that currently have protection applied from being modified..
        /// </summary>
        internal static string Modify_SelectProtectedElements {
            get {
                return ResourceManager.GetString("Modify_SelectProtectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes protection from any selected Element(s) with it currently of this type. This tool can only be ran by administrators as it does not trigger a bypass code to be validated unlike if an end user tries to bypass protection when offered..
        /// </summary>
        internal static string Modify_UnprotectSelectedElements {
            get {
                return ResourceManager.GetString("Modify_UnprotectSelectedElements", resourceCulture);
            }
        }
    }
}
